hystrix:
  image: kbastani/hystrix-dashboard
  ports:
   - "7979:7979"
  links:
   - gateway
   - discovery
discovery:
  image: kbastani/discovery-microservice
  ports:
   - "8761:8761"
consulagent:
  image: progrium/consul
  ports:
   - "8500:8500"
   - "8400:8400"
   - "8600:53/udp"
  command: -server -bootstrap-expect 1 -ui-dir /ui
  net: host
#registrator:
#  image: gliderlabs/registrator
#  volumes:
#   - "/var/run/docker.sock:/tmp/docker.sock"
#  hostname: "registrator"
#  links:
#   - consul
#  command: "consul:8000"
consul:
  image: kbastani/consul-microservice
  ports:
   - "8000:8000"
  net: host
config:
  image: kbastani/config-microservice
  ports:
   - "8888:8888"
  links:
   - discovery
gateway:
  image: kbastani/api-gateway-microservice
  ports:
   - "10000:10000"
  links:
   - discovery
   - config
   - users
   - recommendation
users:
  image: kbastani/users-microservice
  links:
   - discovery
   - config
recommendation:
  image: kbastani/recommendation-microservice
  links:
   - discovery
   - config