spring:
  profiles.active: default
---
spring:
  profiles: default
server:
  port: 9006
neo4j:
  uri: http://192.168.59.103:7474/db/data/
  username: neo4j
  password: graphdb
aws:
  s3:
    url: https://s3.amazonaws.com/dataset-demos